<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="jhet" failures="1" tests="1" name="TestFour" time="23.456" errors="0" timestamp="07 Jun 2024 14:17:58 GMT">
  <testcase classname="tests.FourTest" name="testFour" time="21.213">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at tests.FourTest.testFour(FourTest.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
</testsuite> <!-- TestFour -->
